language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=openduty.settings_dev
install:
  - pip install -r requirements.txt
  - python manage.py syncdb
  - python manage.py migrate
script: "python manage.py test"